# 支持本项目的方式 / Ways to support this project

# GitHub Sponsors
github: [DanOps-1]

# Patreon
# patreon: username

# Open Collective
# open_collective: xray-vpn-oneclick

# Ko-fi
# ko_fi: username

# Buy Me a Coffee
# buy_me_a_coffee: username

# 自定义链接 / Custom links (最多 4 个)
# custom: ["https://your-link.com"]
